# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: caad61f8a21b311cc3ee9683eb88b1b378ec452414669ad54b4d8f501acf224ebd19fc8419869988d7069763b2480fc123c24cd485dd91549ab11e56ae6e14af

test:
  secret_key_base: 4a3c5be4b1ca988153de1c8e915b16b15c415d05bd1dd63fc94ea5617ba2bf6edc0f1140f41060e96e6b08c998191948b03cd3ace830048c89607a52ec77bd47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
